In [24]:
import numpy as np

In [2]:
#Creating numpy array
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
type(a)

numpy.ndarray

In [5]:
import array as ar

In [8]:
ar.array('i',[1,2,3,4,5]) #not useful in data manipulation

array('i', [1, 2, 3, 4, 5])

In [10]:
np.array([1,34,56,67,'vishnu'])

array(['1', '34', '56', '67', 'vishnu'], dtype='<U21')

In [13]:
np.array([1,34,56,67],ndmin=3) #3D

array([[[ 1, 34, 56, 67]]])

In [14]:
np.array([1,34,56,67],ndmin=2) #2D

array([[ 1, 34, 56, 67]])

In [15]:
np.array([1,34,56,67],ndmin=1) #1D

array([ 1, 34, 56, 67])

In [16]:
np.array([1,34,56,67],ndmin=0) #1D and 0D is same

array([ 1, 34, 56, 67])

In [18]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) #3D data  #front plane, back plane


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
a = np.array([5,6,7])

In [28]:
type(a)

numpy.ndarray

In [32]:
np.array([4.7,5,6,7],dtype=complex)

array([4.7+0.j, 5. +0.j, 6. +0.j, 7. +0.j])

In [31]:
np.array([4,5,6,7],dtype=str)   #<U strings

array(['4', '5', '6', '7'], dtype='<U1')

In [33]:
type(np.array([4,5,6,7]))

numpy.ndarray

In [35]:
np.asarray([4,5,6,7],dtype=float)

array([4., 5., 6., 7.])

In [36]:
np.asarray([4,5,6,7],dtype=np.float)

array([4., 5., 6., 7.])

In [40]:
mat = np.matrix([5,6])

In [41]:
mat

matrix([[5, 6]])

In [42]:
type(mat)

numpy.matrix

In [43]:
np.asanyarray(mat) #already mat is in a form of array. so no conversion needed.

matrix([[5, 6]])

In [44]:
l = [1,2,3,4]
np.asanyarray(l) # l is not in form of array. so converted into array.

array([1, 2, 3, 4])

In [48]:
np.fromfunction(lambda i,j : i*j,(3,3)) #own custom function to create array

#  0  1  2
#0 0  0  0
#1 0  1  2
#2 0  2  4 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [49]:
np.fromfunction(lambda i,j : i==j,(3,3))


#  0  1  2
#0 T  F  F
#1 F  T  F
#2 F  F  T

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [55]:
np.fromfunction(lambda i,j: i**i,(3,3),dtype=int)


array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4]])

In [60]:
np.fromstring('11 22 33',sep=" ") #for numerical strings

array([11., 22., 33.])

In [61]:
np.fromstring('4,5,5,2,5',sep=",")

array([4., 5., 5., 2., 5.])

We will only utilize 5 - 10 functions in numpy in real world

In [62]:
b1=np.array([5,6,7,8,9])

In [76]:
b2 = np.array([[4,5,6,7,8,9]])

In [66]:
b3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
b1

array([5, 6, 7, 8, 9])

In [65]:
b2

array([4, 5, 6, 7, 8, 9])

In [68]:
b3 #2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
b1.ndim #how many dimensions

1

In [71]:
b3.ndim

2

In [72]:
b1.size #number of element

5

In [73]:
b3.size

9

In [79]:
b3.shape #3X3 shape

(3, 3)

In [77]:
b1.shape

(5,)

In [78]:
b2.shape

(1, 6)

In [80]:
np.array([(2,3,4,5,6),(3,4,5,6,7)]) #list of tuples
#converted into array'

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [81]:
range(3,10) #lower bound, upper bound

range(3, 10)

In [82]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [87]:
# list(range(2,3.3)) #this is not work for float values. only int values

In [88]:
#for float values like in range, use arange function
list(np.arange(2,6.6,0.5)) #lower, upper, jump

[2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5]

In [91]:
list(np.arange(12,6.6,-0.5))

[12.0, 11.5, 11.0, 10.5, 10.0, 9.5, 9.0, 8.5, 8.0, 7.5, 7.0]

In [96]:
#custom number of data between a custom range
np.linspace(2,5,num=20) 

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

In [95]:
np.linspace(2,5,num=10) 

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [99]:
np.linspace(3,5,num=5) #5 numbers between 3 to 5
#include upper and lower bound also

array([3. , 3.5, 4. , 4.5, 5. ])

In [100]:
np.zeros(2)

array([0., 0.])

In [101]:
np.zeros((3,3)) #input dimensions

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [103]:
b4 = np.zeros((2,2,3))

In [104]:
b4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [105]:
b4.shape

(2, 2, 3)

In [106]:
b4.ndim

3

In [107]:
b4.size

12

In [108]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [109]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
np.ones((3,3)) + 10  #Adds 10 for every array

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [111]:
np.empty(10)  #random elements

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [112]:
np.empty((3,5))

array([[4.67686681e-310, 1.03977794e-312, 1.03977794e-312,
        9.54898106e-313, 1.14587773e-312],
       [1.03977794e-312, 1.23075756e-312, 1.06099790e-312,
        1.01855798e-312, 9.76118064e-313],
       [1.10343781e-312, 1.14587773e-312, 1.08221785e-312,
        3.44981226e+175, 6.81019663e-310]])

In [114]:
#Identity Matrixes
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [115]:
np.eye(4) + 10 

array([[11., 10., 10., 10.],
       [10., 11., 10., 10.],
       [10., 10., 11., 10.],
       [10., 10., 10., 11.]])

In [117]:
np.arange(16) + 20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [118]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
#Reshaping
np.arange(16).reshape(4,4)  #4*4 = 16 elements, this 16 should match

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [122]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [123]:
np.arange(16).reshape(16,1) #(row,column)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [124]:
np.arange(16).reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [125]:
np.arange(16).reshape((2,-1))  #(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [128]:
np.arange(16).reshape((2,-155))  #any negative number   2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [129]:
np.arange(16).reshape((2,-344,2)) # -344 will be understood as 4 which is remaing shape

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [130]:
np.random.rand(2,3)  #row, col

array([[0.13798622, 0.95830059, 0.0436827 ],
       [0.24486478, 0.27498901, 0.16904666]])

In [131]:
np.random.rand(10)  #uniform distribution

array([0.83543493, 0.32217281, 0.58209541, 0.01028912, 0.76820571,
       0.87367822, 0.24268878, 0.77630422, 0.52624799, 0.76684865])

In [133]:
np.random.randn(10)  

array([ 1.87512962,  0.35964809,  0.86760338,  0.34418856,  0.44510406,
       -1.42538947,  1.06959377,  0.4015352 , -1.54598745, -0.22377181])

In [135]:
np.random.randn(2,3) #standard normal distribution mean = 0, std =1

array([[-0.23873132, -0.45211287,  0.14319904],
       [ 0.21851935, -0.54353403,  2.77249982]])

In [140]:
np.random.randint(1,5) #a random value between the range

4

In [143]:
np.random.randint(1,5,(4,3)) #range=(1,5),shape=(4,3)

array([[2, 2, 4],
       [3, 1, 3],
       [2, 1, 3],
       [4, 1, 2]])

In [145]:
#getting same random number  #fix the random values with same seed value
np.random.seed(42)
np.random.randn(10)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [147]:
np.random.seed(42)   #similar to randomstate in ml models
np.random.randn(10)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [164]:
#row wise sorting
b5 = np.random.randint(2,6,(3,4))

In [165]:
b5

array([[5, 3, 4, 3],
       [2, 5, 3, 5],
       [3, 4, 5, 2]])

In [160]:
np.sort(b5)  #row wise sorting

array([[3, 4, 5, 5],
       [2, 2, 4, 5],
       [2, 3, 4, 5]])

In [163]:
#Column wise sorting not working
np.sort(b5,axis=1)

array([[3, 4, 5, 5],
       [2, 2, 4, 5],
       [2, 3, 4, 5]])

In [166]:
b6 = np.random.randint(2,10,(3,3))

In [168]:
b6

array([[4, 4, 4],
       [6, 4, 6],
       [6, 3, 7]])

In [171]:
np.sort(b6,axis=1)

array([[4, 4, 4],
       [4, 6, 6],
       [3, 6, 7]])

In [172]:
np.sort(b6)

array([[4, 4, 4],
       [4, 6, 6],
       [3, 6, 7]])

In [174]:
np.sort(b6,axis=0)

array([[4, 3, 4],
       [6, 4, 6],
       [6, 4, 7]])

In [175]:
np.sort(b6,axis=1,kind='mergesort')

array([[4, 4, 4],
       [4, 6, 6],
       [3, 6, 7]])

In [176]:
np.sort(b6,axis=1,kind='quicksort')

array([[4, 4, 4],
       [4, 6, 6],
       [3, 6, 7]])

In [177]:
b6

array([[4, 4, 4],
       [6, 4, 6],
       [6, 3, 7]])

In [178]:
b6.max()

7

In [179]:
b6[2][2]

7

In [180]:
b6[1][2]

6

In [181]:
b6[1]

array([6, 4, 6])

In [182]:
b6[0:2]

array([[4, 4, 4],
       [6, 4, 6]])

In [184]:
b6[2:0:-1]

array([[6, 3, 7],
       [6, 4, 6]])

In [186]:
b7 = np.random.randint(3,7,(6,6))

In [187]:
b7

array([[4, 5, 4, 6, 5, 6],
       [3, 5, 4, 3, 4, 5],
       [6, 3, 6, 5, 5, 5],
       [3, 5, 4, 5, 3, 6],
       [5, 4, 5, 6, 4, 5],
       [4, 3, 6, 6, 6, 4]])

In [188]:
b7[3]

array([3, 5, 4, 5, 3, 6])

In [189]:
b7[2:5]  #gives 2,3,4 indexes

array([[6, 3, 6, 5, 5, 5],
       [3, 5, 4, 5, 3, 6],
       [5, 4, 5, 6, 4, 5]])

In [190]:
b7[2:6:2]   #last 2 is the jump

array([[6, 3, 6, 5, 5, 5],
       [5, 4, 5, 6, 4, 5]])

In [191]:
b7[2:5,2:4]  #row range, column range slicing

array([[6, 5],
       [4, 5],
       [5, 6]])

In [194]:
b8 = np.random.randint(3,6,(3,4))

In [195]:
b9 = np.random.randint(3,8,(3,4))

In [198]:
b8

array([[3, 3, 5, 5],
       [5, 5, 5, 4],
       [3, 3, 4, 3]])

In [199]:
b9

array([[3, 4, 4, 5],
       [4, 5, 3, 7],
       [3, 3, 3, 5]])

In [196]:
b8/0  #infinity = inf

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [197]:
b8/b9

array([[1.        , 0.75      , 1.25      , 1.        ],
       [1.25      , 1.        , 1.66666667, 0.57142857],
       [1.        , 1.        , 1.33333333, 0.6       ]])

In [200]:
b8*b9

array([[ 9, 12, 20, 25],
       [20, 25, 15, 28],
       [ 9,  9, 12, 15]])

In [201]:
b10 = np.random.randint(3,6,(3,3))

In [202]:
b10

array([[5, 5, 3],
       [3, 5, 4],
       [3, 3, 5]])

In [204]:
#if number of elements are not same, it will give error
#element wise multiplication
#b9/b10

In [207]:
#matrix multiplication
b8.T@b9

array([[38, 46, 36, 65],
       [38, 46, 36, 65],
       [47, 57, 47, 80],
       [40, 49, 41, 68]])

In [208]:
b8 ** 3

array([[ 27,  27, 125, 125],
       [125, 125, 125,  64],
       [ 27,  27,  64,  27]])